name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    name: Release Drafter
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@c345907820e0396f6f44bcfd9ac4763325f8feb0  # v7.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
