name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv --system

      - name: Install dependencies
        run: |
          uv pip install -r requirements-test.txt --system

      - name: Test with pytest
        run: pytest --timeout=30 --cov=imgw_pib --cov-report=xml --error-for-skips
