name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Test:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -r requirements-test.txt --system
      
      - name: Test with ruff
        run: |
          ruff check .
          ruff format --check .

      - name: Test with mypy
        run: mypy imgw_pib

      - name: Test with pytest
        run: pytest --timeout=30 --cov=imgw_pib --cov-report=xml --error-for-skips

      - name: Coverage
        run: coverage report --fail-under=79
